name: CI

on:
  push:
    branches:
      - glyphs3
      - master
  pull_request:
    branches:
      - glyphs3
      - master
  workflow_dispatch:

jobs:
  build:
    name: Validation
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Property List
        run: plutil -lint packages.plist
